name: Pytest API and CLI Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install and initialize Taskwarrior AUT
        run: |
          sudo apt-get install taskwarrior
#          yes | task version
      - name: Run tests
        run: |
          pytest -v
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report
